### ISSUE TITLE
Setup and Driver

### ISSUE THREAD

**Issue by Synoia** [fenlogic/vga666#10]
Could you please post a link to the setup instructions and driver download information?

Thanks

**Comment by gertvanloo** [comment]
There is nothing to download or install. The drivers are part of the Raspberrypi software. 
For all matters related to software go to the Raspberry-Pi website: www.raspberrypi.org
You also have to look there for resolution, bit clock etc. 

There is a section in the beginners forum which answers most VGA questions: 
www.raspberrypi.org/forums/viewtopic.php?f=91&t=94424
