### ISSUE TITLE
the GPIO21

### ISSUE THREAD

**Issue by melaymei** [fenlogic/vga666#12]
I want to use the GPIO 21 for I2S out.
but it be used in DPI RGB565.
Can i change the DPI pin?
Sorry for my poor english.

**Comment by gertvanloo** [comment]
The DPI outputs are  hard coded . You can find them in [this ]( https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=94424&sid=acaa30a75f1b601c9fb88893efcb99e8#p1238180) table. 
You have several options:
1/  Use DPI mode 2. (565 mode) 
2/  Use DPI mode 4 (565 mode) and loose RED colour bit 3. Reduces the number of colours.
3/  Use DPI mode 6 (666) and loose RED colour bit 2 and 3. Reduces the number of colours.
4/  Use DPI mode 7. (Don't use bits 0 or 1 of any colour)
In all cases you have to wire up your own VGA connector.
