### ISSUE TITLE
Flickering with VGA666 on Raspbian Buster

### ISSUE THREAD

**Issue by alessioscand** [fenlogic/vga666#13]
Hello,
the picture of a VGA666 on Raspbian Buster (Raspberry Pi 4) it's flickering like this:
https://youtu.be/5f5hpGrPpZk

I've tested different settings (resolution, refresh, video driver etc.) and even different hardware (GPIO cable, VGA666) but the problem persist.

Thank you.

**Comment by gertvanloo** [comment]
This is a known issue. It is mentioned in the assembly manual as "bit crawl". The cause is the cross-over talk between the various analogue signals. It gets worse with longer cables and higher frequencies. Some monitors are more susceptible then others.

**Comment by alessioscand** [comment]
Thank you for your feedback. If this is the problem ("bitcrawl") why does it happen only on Raspbian Buster and/or RPi 4, and not on Raspbian Stretch / RPi 3?

I'm using same monitor and same parts, and I get no issues with Raspbian Stretch and RPi3 (pardon me I took it for granted in my previous post).

It seems and issue related with the use of RPi4 and/or Raspbian Buster.

**Comment by linuxenko** [comment]
Hi @alessioscand. Did you make it work properly on RPI 4 ?
