### ISSUE TITLE
VGA Pins 4, 9, 11, 12, and 15 - "nc" means "connected together"

### ISSUE THREAD

**Issue by 6by9** [fenlogic/vga666#15]
I know this is pretty much a dead project, but logging for information.

Schematic lists the above pins on the 15pin-HD D as "nc", which normally means "not connected".

PCB design has connected them all together, presumably as a net called "nc"!

That caused me a fair amount of head scratching when I was trying to hook I2C level shifters onto pins 12 &15 from Pi GPIOs 0&1 to be able to read the display EDID (works quite nicely).

**Comment by gertvanloo** [comment]
I am rather surprised. I have never noticed that those pins where interconnected. In the schematic they do not have a net name. (the NC is  just a label on  of the VGA connector) and as such they **_should_** have been unconnected. In my blind faith of the CAD tools I must have routed all traces as shown to me by the PCB tool without checking them against the schematic. You are right, there is no need or reason why they should be connected together.
