### ISSUE TITLE
Disabling and Enabling the VGA output

### ISSUE THREAD

**Issue by clacktronics** [fenlogic/vga666#2]
Is there a way to disable the output ( as in the screen sees no signal ) as tvservice does not control this output?

Thanks!
-Ben

**Comment by gertvanloo** [comment]
Not with the hardware. For  software feature : you have to ask that question on the Raspberry-Pi forum: www.raspberrypi.org/forums/

**Comment by clacktronics** [comment]
Ah apologies at the time I did not realize it is in the binary blob thankyou for replying.
